- name: Install OpenSCAP scanner and SCAP Security Guide
  hosts: win19server
  gather_facts: false
  tasks:
    - name: Copy msi installer of openscanner
      ansible.windows.win_copy:
        src: /home/mario/Downloads/OpenSCAP-1.3.0-win32.msi
        dest: C:\Users\ansible2019server\AppData\Local\Temp

    - name: Install openscanner with msi
      ansible.windows.win_package:
        path: C:\Users\ansible2019server\AppData\Local\Temp\OpenSCAP-1.3.0-win32.msi

    - name: Send SCAP file to the Windows Server 2019
      ansible.windows.win_copy:
        src: /home/mario/Documents/scap/U_MS_Windows_Server_2019_V2R4_STIG_SCAP_1-2_Benchmark.xml
        dest: C:\Temp

    - name: Set facts for oscap command
      set_fact:
        command: "C:\\Program Files (x86)\\OpenSCAP 1.3.0\\oscap.exe"
        profile: "xccdf_mil.disa.stig_profile_MAC-1_Classified"
        arf_file: "C:\\Temp\\arf.xml"
        report_file: "C:\\Temp\\report.html"
        scap_file: "C:\\Temp\\U_MS_Windows_Server_2019_V2R4_STIG_SCAP_1-2_Benchmark.xml"
    
    - name: Delete report.html file if exists
      ansible.windows.win_file:
        path: C:\Temp\report.html
        state: absent

    - name: Run OpenSCAP evaluation for STIG DISA Windows Server 2019 Benchmark 
      ansible.windows.win_shell: |
        & "{{ command }}" xccdf eval --oval-results --profile "{{ profile }}" --results-arf "{{ arf_file }}" --report "{{ report_file }}" "{{ scap_file }}"
      register: oscap_output

    - name: Display oscap command output
      debug:
        var: oscap_output.stdout

    - name: Fetch remote report html file
      fetch:
        src: C:\Temp\report.html
        dest: /home/mario/Documents/oscap-ansible-project/Windows2019Server/
        flat: yes
